[I 2021-02-05 22:09:00.973 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-02-05 22:09:01.132 ServerApp] nbclassic | extension was successfully linked.
[I 2021-02-05 22:09:01.173 LabApp] JupyterLab extension loaded from /home/rluo/anaconda3/envs/krr/lib/python3.8/site-packages/jupyterlab
[I 2021-02-05 22:09:01.173 LabApp] JupyterLab application directory is /home/rluo/anaconda3/envs/krr/share/jupyter/lab
[I 2021-02-05 22:09:01.176 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-02-05 22:09:01.179 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-02-05 22:09:01.179 ServerApp] Serving notebooks from local directory: /home/rluo/raid/projects/KRR/syn_time_accountant
[I 2021-02-05 22:09:01.179 ServerApp] Jupyter Server 1.2.2 is running at:
[I 2021-02-05 22:09:01.179 ServerApp] http://localhost:8888/lab?token=4ac49a03fd5a8b5940fdc11581021d9722136da15e7bd42f
[I 2021-02-05 22:09:01.179 ServerApp]  or http://127.0.0.1:8888/lab?token=4ac49a03fd5a8b5940fdc11581021d9722136da15e7bd42f
[I 2021-02-05 22:09:01.179 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-02-05 22:09:01.182 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/rluo/.local/share/jupyter/runtime/jpserver-3043160-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=4ac49a03fd5a8b5940fdc11581021d9722136da15e7bd42f
     or http://127.0.0.1:8888/lab?token=4ac49a03fd5a8b5940fdc11581021d9722136da15e7bd42f
[W 2021-02-05 22:09:08.647 ServerApp] 401 POST /login?next=%2Flab (127.0.0.1) 15.42ms referer=http://localhost:9000/login?next=%2Flab
[E 2021-02-05 22:09:14.370 ServerApp] Uncaught exception POST /login?next=%2Flab (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:9000', method='POST', uri='/login?next=%2Flab', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/rluo/anaconda3/envs/krr/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/rluo/anaconda3/envs/krr/lib/python3.8/site-packages/jupyter_server/auth/login.py", line 90, in post
        set_password(new_password, config_file=config_file)
      File "/home/rluo/anaconda3/envs/krr/lib/python3.8/site-packages/jupyter_server/auth/security.py", line 147, in set_password
        config.ServerApp.password = hashed_password
      File "/home/rluo/anaconda3/envs/krr/lib/python3.8/contextlib.py", line 120, in __exit__
        next(self.gen)
      File "/home/rluo/anaconda3/envs/krr/lib/python3.8/site-packages/jupyter_server/auth/security.py", line 131, in persist_config
        with io.open(config_file, 'w', encoding='utf8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/rluo/.jupyter/jupyter_notebook_config.json'
[E 2021-02-05 22:09:14.379 ServerApp] {
      "Host": "localhost:9000",
      "Connection": "keep-alive",
      "Content-Length": "149",
      "Cache-Control": "max-age=0",
      "Origin": "http://localhost:9000",
      "Upgrade-Insecure-Requests": "1",
      "Dnt": "1",
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Dest": "document",
      "Referer": "http://localhost:9000/login?next=%2Flab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1612386951|23:username-localhost-8888|44:ZmE1YmNkZTUxODM3NDNiNDg0MTY1ZjI2MGY5NzY4ZmQ=|f451e1f7cd1417e50729512e769733972546681044760cfdcdca8a1693821284\"; _xsrf=2|03d24016|da36962848bdbc1b5c4240f8539e2eaf|1612580904"
    }
[E 2021-02-05 22:09:14.379 ServerApp] 500 POST /login?next=%2Flab (127.0.0.1) 10.55ms referer=http://localhost:9000/login?next=%2Flab
[I 2021-02-05 22:09:19.065 ServerApp] 302 GET / (127.0.0.1) 0.82ms
[W 2021-02-05 22:09:29.389 LabApp] Could not determine jupyterlab build status without nodejs
[I 2021-02-05 22:09:37.709 ServerApp] Creating new notebook in 
[I 2021-02-05 22:09:37.733 ServerApp] Writing notebook-signing key to /home/rluo/.local/share/jupyter/notebook_secret
[I 2021-02-05 22:09:38.672 ServerApp] Kernel started: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 22:11:38.253 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:12:33.424 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 22:13:13.393 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 22:13:38.349 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:15:38.462 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:18:45.061 ServerApp] Creating new file in /naive-scrcpy-client
[I 2021-02-05 22:19:11.562 ServerApp] Saving file at /naive-scrcpy-client/__init__.py
[I 2021-02-05 22:21:38.610 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:23:38.725 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:24:29.830 ServerApp] Saving file at /naive-scrcpy-client/__init__.py
[I 2021-02-05 22:25:00.479 ServerApp] Saving file at /naive_scrcpy_client/__init__.py
[I 2021-02-05 22:25:20.315 ServerApp] Saving file at /naive_scrcpy_client/__init__.py
[I 2021-02-05 22:25:25.264 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 22:25:38.877 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:27:39.018 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:29:22.117 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:29:27.590 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:31:29.903 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 22:31:34.998 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 22:31:37.903 ServerApp] Kernel restarted: f56aefbf-953d-4c11-aab4-b5f645075a31
error: more than one device/emulator
error: more than one device/emulator
[I 2021-02-05 22:33:27.817 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:33:35.189 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 22:37:36.133 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 22:39:36.300 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 22:39:48.535 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 22:39:53.587 ServerApp] Kernel restarted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 22:39:59.530 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 22:40:03.031 ServerApp] Kernel restarted: f56aefbf-953d-4c11-aab4-b5f645075a31
error: more than one device/emulator
error: more than one device/emulator
[I 2021-02-05 22:40:13.693 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 22:40:17.217 ServerApp] Kernel restarted: f56aefbf-953d-4c11-aab4-b5f645075a31
error: more than one device/emulator
error: more than one device/emulator
[I 2021-02-05 22:40:57.301 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 22:41:00.972 ServerApp] Kernel restarted: f56aefbf-953d-4c11-aab4-b5f645075a31
error: more than one device/emulator
error: more than one device/emulator
[I 2021-02-05 22:41:28.636 ServerApp] Saving file at /scrcpy.ipynb
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
[I 2021-02-05 22:43:28.750 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:43:31.792 ServerApp] Kernel restarted: f56aefbf-953d-4c11-aab4-b5f645075a31
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
[I 2021-02-05 22:44:54.527 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 22:44:56.797 ServerApp] Kernel restarted: f56aefbf-953d-4c11-aab4-b5f645075a31
error: more than one device/emulator
error: more than one device/emulator
[I 2021-02-05 22:45:28.903 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:46:28.705 ServerApp] Kernel restarted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 22:46:56.038 ServerApp] Kernel restarted: f56aefbf-953d-4c11-aab4-b5f645075a31
error: more than one device/emulator
error: more than one device/emulator
[I 2021-02-05 22:47:12.564 ServerApp] Kernel restarted: f56aefbf-953d-4c11-aab4-b5f645075a31
error: more than one device/emulator
error: more than one device/emulator
[I 2021-02-05 22:47:29.089 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:48:06.566 ServerApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel f56aefbf-953d-4c11-aab4-b5f645075a31 restarted
kernel f56aefbf-953d-4c11-aab4-b5f645075a31 restarted
[I 2021-02-05 22:48:06.657 ServerApp] Starting buffering for f56aefbf-953d-4c11-aab4-b5f645075a31:8ef32174-9052-4a34-a18f-ca46e419d7f4
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
[I 2021-02-05 22:49:29.208 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:49:56.073 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 22:49:59.084 ServerApp] Kernel restarted: f56aefbf-953d-4c11-aab4-b5f645075a31
adb: usage: -s requires an argument
adb: usage: -s requires an argument
[I 2021-02-05 22:51:29.424 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 22:53:29.570 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 23:05:31.713 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 23:15:31.864 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 23:17:32.048 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 23:19:32.212 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 23:21:32.494 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 23:29:08.973 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 23:29:32.641 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 23:29:55.511 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 23:31:32.768 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 23:31:44.581 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 23:32:53.651 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 23:33:07.958 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 23:33:11.366 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 23:33:14.084 ServerApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel f56aefbf-953d-4c11-aab4-b5f645075a31 restarted
kernel f56aefbf-953d-4c11-aab4-b5f645075a31 restarted
[I 2021-02-05 23:33:14.101 ServerApp] Starting buffering for f56aefbf-953d-4c11-aab4-b5f645075a31:8ef32174-9052-4a34-a18f-ca46e419d7f4
[I 2021-02-05 23:33:32.853 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 23:34:00.860 ServerApp] Saving file at /naive_scrcpy_client/NaiveScrcpyClient.py
[I 2021-02-05 23:34:17.068 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 23:34:25.320 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 23:34:33.286 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 23:35:33.060 ServerApp] Saving file at /scrcpy.ipynb
ffplay version 4.2.4-1ubuntu0.1 Copyright (c) 2003-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Could not initialize SDL - No available video device
(Did you set the DISPLAY variable?)
[I 2021-02-05 23:36:04.115 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 23:36:53.677 ServerApp] Kernel interrupted: f56aefbf-953d-4c11-aab4-b5f645075a31
[I 2021-02-05 23:37:33.217 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-05 23:51:33.925 ServerApp] Saving file at /scrcpy.ipynb
[I 2021-02-06 16:40:00.189 ServerApp] Starting buffering for f56aefbf-953d-4c11-aab4-b5f645075a31:075e7e65-62e1-47a3-a4b2-dae28b14d28f
[W 2021-02-08 23:58:24.095 ServerApp] Clearing invalid/expired login cookie username-localhost-8888
[W 2021-02-08 23:58:24.097 LabApp] Clearing invalid/expired login cookie username-localhost-8888
[I 2021-02-08 23:58:24.097 LabApp] 302 GET /lab/tree/scrcpy.ipynb (127.0.0.1) 2.90ms
[W 2021-02-08 23:58:28.177 ServerApp] 401 POST /login?next=%2Flab%2Ftree%2Fscrcpy.ipynb (127.0.0.1) 2.22ms referer=http://localhost:8888/login?next=%2Flab%2Ftree%2Fscrcpy.ipynb
[I 2021-02-08 23:58:44.213 ServerApp] Wrote hashed password to /home/rluo/.jupyter/jupyter_notebook_config.json
[I 2021-02-08 23:58:44.213 ServerApp] 302 POST /login?next=%2Flab%2Ftree%2Fscrcpy.ipynb (127.0.0.1) 3.19ms
[W 2021-02-08 23:58:47.587 LabApp] Could not determine jupyterlab build status without nodejs
[W 2021-02-08 23:58:48.473 ServerApp] Notebook scrcpy.ipynb is not trusted
[I 2021-02-08 23:58:53.205 ServerApp] Creating new notebook in 
[I 2021-02-08 23:58:53.505 ServerApp] Kernel started: e2f4b94f-b2c1-42c0-bcfc-b92dc65b0ed3
[I 2021-02-09 00:00:20.752 ServerApp] Saving file at /helpers/__init__.py
[I 2021-02-09 00:00:53.440 ServerApp] Saving file at /pyav.ipynb
Aborted 
